### ISSUE TITLE
Change the input parameters in the bigData folder to the same approach as in the rest

### ISSUE THREAD

**Issue by josecamachop** [josecamachop/MEDA-Toolbox#79]

**Comment by JesusGarSan** [comment]
I am going to ahve to do this little by little, but stuff won't work correctly until everythin si changed, so I will use this to track my progress in the version-2-Big_data branch.

I will mark with X the files that I have already updated.

Some functions don't take  optional arguments, so I won't be touching those.
Same thing goes for funtions in internal/. Since we don't expect users to sue those, I won't change the input parameter structure

bigData/
├── internal/
│   ├── X addData.m
│   ├── X addIndices.m
│   ├── X cfilesys.m
│   ├── X checkLmodel.m
│   ├── X psc.m
│   ├── X readData.m
│   └── X readIndices.m
├── modelSel/
│   ├── varLpca.m
│   └── varLpls.m
├── modelViz/
│   ├── leveragesLpca.m
│   ├── leveragesLpls.m
│   ├── loadingsLpca.m
│   ├── loadingsLpls.m
│   ├── medaLpca.m
│   ├── medaLpls.m
│   ├── mscpAdicov.m
│   ├── mscpLpca.m
│   ├── mscpLpls.m
│   ├── omedaLpca.m
│   ├── omedaLpls.m
│   ├── scoresL.m
│   ├── scoresLpca.m
│   └── scoresLpls.m
├── initLmodel.m
├── Lgpca.m
├── X Lpca.m
├── X Lpls.m
├── X preprocess2Di.m
├── X selectVars.m
├── updateEwma.m
├── updateIterative.m
└── README.txt

**Comment by JesusGarSan** [comment]
I am getting rid of the "Complete call" part of the help, as the example would need to include the value fo the variables.

a proper example will be given in "EXAMPLE OF USE"

**Comment by JesusGarSan** [comment]
All input parameters have been updated and pushed to the version-2-Big_data branch

**Comment by JesusGarSan** [comment]
updated README files and created tests folder
